### ISSUE TITLE
Claim Account not Working

### ISSUE THREAD

**Issue by bindlerj** [cpimhoff/DogGoat#48] opened 2016-04-02 01:02 UTC
Site looks dope tho!!!!!!

**Comment by cpimhoff** [comment] 2016-04-02 05:53
Thanks for using the IssueTracker Julia!

A lot of folks reported this, and so I looked into it.
**It is now fixed. I have confirmed you can create accounts now.**

The issue was that Invitations and Member Accounts must have unique emails to prevent inviting folks who are already members. When you (attempted to) create a new account, the invitation was set to be deleted _after_ the Member account was created. When the Member ran validations, the invitation was still around (and had the same email).

I fixed it by having the invitation delete _before_ the member account is created. If and only if the member account fails for some other reason, the invitation is restored (so no worries there).

The issue slipped through testing because this particular set of validations was added after the scaffold (and testing) for registering a new account.

**Closed as completed by cpimhoff** 2016-04-02 05:53 UTC
Labels: bug
